<?xml version="1.0" encoding="UTF-8"?>
<tileset version="1.8" tiledversion="1.8.4" name="Tide" tilewidth="16" tileheight="16" tilecount="80" columns="10">
 <image source="TideTileset.png" width="160" height="128"/>
 <tile id="0" type="Wall"/>
 <tile id="1" type="Wall"/>
 <tile id="2" type="Wall"/>
 <tile id="3" type="Wall"/>
 <tile id="4" type="Wall"/>
 <tile id="5" type="Wall"/>
 <tile id="6" type="Wall"/>
 <tile id="7" type="Wall"/>
 <tile id="8" type="Wall"/>
 <tile id="9" type="Wall"/>
 <tile id="10" type="Wall"/>
 <tile id="11" type="Wall"/>
 <tile id="12" type="Wall"/>
 <tile id="13" type="Wall"/>
 <tile id="14" type="Wall"/>
 <tile id="15" type="Wall"/>
 <tile id="16" type="Wall"/>
 <tile id="17" type="Wall"/>
 <tile id="18" type="Wall"/>
 <tile id="19" type="Wall"/>
 <tile id="20" type="Wall"/>
 <tile id="21" type="Wall"/>
 <tile id="22" type="Wall"/>
 <tile id="23" type="Wall"/>
 <tile id="24" type="Wall"/>
 <tile id="25" type="Wall"/>
 <tile id="26" type="Wall"/>
 <tile id="27" type="Wall"/>
 <tile id="28" type="Wall"/>
 <tile id="29" type="Wall"/>
 <tile id="30" type="Wall"/>
 <tile id="31" type="Wall"/>
 <tile id="32" type="Wall"/>
 <tile id="33" type="Wall"/>
 <tile id="34" type="Wall"/>
 <tile id="35" type="Wall"/>
 <tile id="36" type="Wall"/>
 <tile id="37" type="Wall"/>
 <tile id="38" type="Wall"/>
 <tile id="39" type="Wall"/>
 <tile id="40" type="Wall"/>
 <tile id="42" type="Wall"/>
 <tile id="43" type="Wall"/>
 <tile id="44" type="Wall"/>
 <tile id="45" type="Wall"/>
 <tile id="46" type="Wall"/>
 <tile id="47" type="Wall"/>
 <tile id="49" type="Wall"/>
 <tile id="51" type="Spike"/>
 <tile id="52" type="Wall"/>
 <tile id="53" type="Wall"/>
 <tile id="54" type="Wall"/>
 <tile id="55" type="Wall"/>
 <tile id="56" type="Wall"/>
 <tile id="57" type="Wall"/>
 <tile id="58" type="Wall"/>
 <tile id="59" type="Wall"/>
 <tile id="60" type="Spike"/>
 <tile id="61" type="Wall"/>
 <tile id="62" type="Spike"/>
 <tile id="63" type="Wall"/>
 <tile id="64" type="Wall"/>
 <tile id="65" type="Wall"/>
 <tile id="66" type="Wall"/>
 <tile id="67" type="Wall"/>
 <tile id="68" type="Wall"/>
 <tile id="69" type="Wall"/>
 <tile id="71" type="Spike"/>
 <tile id="73" type="Wall"/>
 <tile id="74" type="Wall"/>
 <tile id="75" type="Wall"/>
 <tile id="76" type="Wall"/>
 <tile id="77" type="Wall"/>
 <tile id="78" type="Wall"/>
 <tile id="79" type="Wall"/>
</tileset>
